services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=sleweb.settings
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=sleweb
      - POSTGRES_USER=sleweb
      - POSTGRES_PASSWORD=sleweb
    depends_on:
      - db
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=sleweb
      - POSTGRES_USER=sleweb
      - POSTGRES_PASSWORD=sleweb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:


